### ISSUE TITLE
Use a different format for date

### ISSUE THREAD

**Issue by impredicative** [lucaionescu/mini-yahoo-finance-api#1]
Using date in the format `dd-mm-yyy`, e.g. 31-01-2018, is not geographically agnostic and makes code prone to serious bugs. It is not okay to use the `dd-mm-yyy` or the `mm-dd-yyy` formats. Please either use `yyyy-mm-dd` (preferred) or otherwise accept a date object.

**Comment by lucaionescu** [comment]
Hi, thanks for reaching out, this is a good point. I don't know when I will be able to implement this, but feel free to work on this and create a PR if you like to!

**Comment by impredicative** [comment]
Thank you. I will be sure to try the package.
